server.port = 8080

logging.file=/worldweather/logs/worldweather.log

spring.datasource.url=jdbc:postgresql://ep-old-term-a1lzy708-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&ssl=true
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8Qehu3WVZpiL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
